import { createHash } from 'node:crypto';
import { createReadStream } from 'node:fs';
import { lstat, readdir, readlink } from 'node:fs/promises';
import { join } from 'node:path';
import { git } from '../git/worktree.js';

export type WorkspaceSnapshot = Map<string, string>;

/** Compare against the actual starting workspace, including already dirty files.
 * Git supplies tracked paths in otherwise excluded dependency directories. Symlinks
 * are recorded without following them outside the selected workspace.
 */
export async function captureWorkspaceSnapshot(root: string): Promise<WorkspaceSnapshot> {
  const paths = new Set<string>();
  async function walk(relative: string): Promise<void> {
    for (const entry of await readdir(join(root, relative), { withFileTypes: true })) {
      if (entry.name === '.git') continue;
      const path = relative ? `${relative}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        // Session audit/telemetry is generated by the harness, not agent edits.
        if (entry.name !== 'node_modules' && path !== '.bsh/local') await walk(path);
      } else {
        paths.add(path);
      }
    }
  }
  await walk('');
  // A non-Git workspace is supported too. NUL delimiters preserve unusual names.
  const tracked = await git(root, ['ls-files', '-z']).catch(() => '');
  for (const path of tracked.split('\0').filter(Boolean)) {
    if (!path.startsWith('.bsh/local/')) paths.add(path);
  }
  const snapshot: WorkspaceSnapshot = new Map();
  for (const path of paths) {
    try {
      const absolute = join(root, path);
      const stat = await lstat(absolute);
      if (stat.isSymbolicLink()) {
        snapshot.set(path, `symlink:${await readlink(absolute)}`);
      } else if (stat.isFile()) {
        const hash = createHash('sha256');
        for await (const chunk of createReadStream(absolute)) hash.update(chunk);
        const digest = hash.digest('hex');
        snapshot.set(path, `file:${stat.mode & 0o777}:${digest}`);
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
    }
  }
  return snapshot;
}

export function observedChangedFiles(before: WorkspaceSnapshot, after: WorkspaceSnapshot): string[] {
  return [...new Set([...before.keys(), ...after.keys()])]
    .filter((path) => before.get(path) !== after.get(path))
    .sort();
}
